### PR TITLE
GNOME 42.3 Rebase

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by 13r0ck — DISMISSED** [review]

**Comment by gangwerz** [comment]
After adding the `testing-mutter-pr31` and `testing-gnome-shell-pr119` ([gnome-shell 119](https://github.com/pop-os/gnome-shell/pull/119)) repos, and running `sudo apt update` & `sudo apt upgrade`, the packages below are held back:
- `gir1.2-mutter-10`
- `libmutter-10-0`
- gnome-shell
- gnome-shell-common
- gnome-shell-extension-prefs

If I try running an `apt full-upgrade` instead, and both`gir1.2-mutter-10` & `libmutter-10-0` remain held back, but I can upgrade `gnome-shell` and `mutter`.

Upgrading with Pop Shop installed all the updates, but the same 2 packages are being held back if I attempt an upgrade from a Terminal.

An `apt policy` of both packages shows that version 42.3 is available from the `testing-mutter-pr31` repo.

**Comment by mmstick** [comment]
@gangwerz The mutter package failed to build. It is working now.

**Comment by gangwerz** [comment]
> @gangwerz The mutter package failed to build. It is working now.

I performed an OS refresh, then added the `gnome` staging repo. I am now seeing the packages below being held back when I `apt upgrade`:
- `gnome-shell`
- `gnome-shell-common`
- `gnome-shell-extension-prefs`

However, Mutter seems to be able to upgrade. The below packages are queued to upgrade:
- `gir1.2-mutter-10`
- `libmutter-10-0`
- `mutter-common`
---

If I instead perform an `apt full-upgrade`, both the `gnome-shell`- and the `mutter`-related packages are able to upgrade.

Additionally, with a `full-upgrade`, APT is now installing `gir1.2-gweather-4.0` as well. I suspect this is the reason `gnome-shell` is held back when using `apt upgrade`.

I uses Pop Shop to upgrade, and `gir1.2-gweather-4.0` was installed and all the upgrades were installed successfully. So this may only be an issue for our CLI updaters as it is now.

I will proceed with testing the shell for now, but I can retest the upgrade process if we make any changes to the packaging.

**Review by gangwerz — APPROVED** [review]
Changes look good!

See the paired [GNOME Shell PR](https://github.com/pop-os/gnome-shell/pull/119#pullrequestreview-1048395909) for more information.

**Pull request merged**
