### PR TITLE
Mutter 42.9

### PR DESCRIPTION
**Pull request by jackpot51**
Update from https://launchpad.net/ubuntu/+source/mutter/42.9-0ubuntu4, should see if this helps with GPU hangs.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by leviport** [comment]
I still got a GPU hang on my oryp9 with a USB-C display. I'll keep running it to see if it at least became less prevalent.

**Comment by mmstick** [comment]
@leviport Someone mentioned disabling the HiDPI Daemon fixed their freezing. That may be something to try.

**Comment by leviport** [comment]
I've had that disabled on my install for a long time, so I'm not sure that's related

**Comment by leviport** [comment]
Although I did notice that the "Fractional Scaling" switch was turned on in my Display settings. I didn't have a fractional scaling factor set, but I'll turn it off and see if that makes a difference.

**Comment by myth5** [comment]
upstream https://launchpad.net/ubuntu/+source/mutter/42.9-0ubuntu5

any release plan?

i have a mouse cursor stutters problem, that maybe fixed,
like this https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2023766

**Pull request merged**
