### PR TITLE
fix: Fix Java applications like IntelliJ IDEA from crashing GNOME Shell

### PR DESCRIPTION
**Pull request by mmstick**
Upstream MR: https://gitlab.gnome.org/GNOME/mutter/merge_requests/895

### CODE REVIEW

**Review by Janvanoorschot — DISMISSED** [review]
Unfamiliar with this code-base, but the code looks ok and addresses the issue.

**Review by jackpot51 — DISMISSED** [review]

**Comment by mmstick** [comment]
@pop-os/quality-assurance Could we get a quick test for this? I've been using it on all of my systems  over the last ~3 weeks, and haven't encountered any issues. It does prevent anyone from using IntelliJ IDEs on Pop.

**Comment by leviport** [comment]
I'll take a look!

**Comment by leviport** [comment]
I was unable to reproduce the issue on any of the versions of IntelliJ that I tried. It looks like this was merged upstream, so I think we will wait for it to come downstream, which should happen pretty soon.

**Comment by Janvanoorschot** [comment]
@leviport I am using version 19.10 of PopOs and Intellij 2019.3 (Ultimate), both the latest version upgraded to the hilt. The problem is still there and for me it is a show-stopper (i can not create JVM's for my docker-based Python projects in Intellij). See my bug report in Intellij bugtracker to see reprodure my scenario: https://youtrack.jetbrains.com/issue/IDEA-226221.

**Comment by Janvanoorschot** [comment]
@leviport I am using version 19.10 of PopOs and Intellij 2019.3 (Ultimate), both the latest version upgraded to the hilt. The problem is still there and for me it is a show-stopper (i can not create JVM's for my docker-based Python projects in Intellij). See my bug report in Intellij bugtracker to  reproduce my scenario: https://youtrack.jetbrains.com/issue/IDEA-226221.

**Comment by leviport** [comment]
Hi @Janvanoorschot , thanks for providing a link to that issue. It gives me more info, however I'm still unable to see the same issue happen. Since I'm not very familiar with setting up IntelliJ IDEA for Python projects, can you give me a rundown of how to get to a point where I can reproduce the issue reliably? I was able to install the Python plugin, but I'm confused how you get from adding a Python SDK to editing Docker configuration files.

**Comment by Janvanoorschot** [comment]
Hi @leviport, i double checked and the crash still occurs on my computers. 

Do note my remarks in the Intellij bug report stating that the bug only happens when the folder/file selection window is on my first screen. On my home computer, where i only have one screen the crash always happens. On my work computer where i have two screens i can avoid the crash by dragging the folder/file selection window to the secondary screen.

I can show you the crash in a Zoom session although we will loose connection when the crash occurs ;)

You should be able to recreate the crash by creating an empty python project and then try to create the JDK as described in my Intellij bug report. You do not need docker-compose "*.yml" files since the crash occurs before you can select them.

Please let me know how i can help since i really need this bugger to be fixed.

**Comment by Janvanoorschot** [comment]
Hi @leviport, i have made a Kazam screen capture of the crash and will attempt to attach it to this comment (its an mp4 inside a zip since it would not allow to upload the mp4 directly)
[Intellij_PopOs_Crash_Incl.zip](https://github.com/pop-os/mutter/files/3982472/Intellij_PopOs_Crash_Incl.zip)

**Comment by leviport** [comment]
Thank you for that video, @Janvanoorschot! I'm currently juggling a few different projects, and I didn't get a chance to take another look at this issue today. I'm putting it on my schedule for tomorrow though, so I should have more info then. With your video, I believe I'll have a much better time replicating the issue so I can test this fix.

**Comment by Janvanoorschot** [comment]
@leviport, Sorry to add again something but i am testing things on a Thinkpad laptop running PopOs 19.10. It turns out you need to have the Docker Server defined in the last screen for the crash to occur. When the Docker Server field is empty, the crash does not occur. It is absolutely repeatable. I have cleared the field, no crash. Define a server in the field, crash. Clear the field, no crash. Note that this is on a laptop without any extra screens attached. If you like i can create another mp4 of this, let me know.

**Review by leviport — APPROVED** [review]
I am now able to reproduce the issue, and I can verify that this patch addresses it. I believe this patch is ready to merge. Thank you @Janvanoorschot for your help in reproducing the issue!

**Review by crawfxrd — APPROVED** [review]

**Comment by Janvanoorschot** [comment]
@leviport Fixed!!!! Saw a libmutter upgrade coming in this morning and i am good to go again! You guys are my hero's for this last day of the year. Give me a shout if i can return the favour someday. Thanks ... Jan.

**Comment by jbrains** [comment]
One more report of apparent improvement in stability due to this update.

**Pull request merged**
