### PR TITLE
Rebase groovy

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
Pop: 20.10
Hardware: lemp9

Initial tests look good. I've run it through standard window manager functions in both X11 and Wayland. 
Fractional scaling also works as expected. 

Will test more tomorrow.

**Comment by bflanagin** [comment]
Screenshot from 2021-02-23 13-52-02

Not sure how to describe the issue however the screenshot above might be description enough. When using fractional scaling if you use the Revert Settings option instead of Keep settings the windows resize in strange ways. Most just lose their geometry and location, but in the case of Fire Fox you get this strange partially zoomed in window. This doesn't occur in the standard non-fractional scaling mode. 

Seen on Gaze15 and Lemp9.

**Comment by bflanagin** [comment]
As an amendment to the bug above. I was able to replicate the issue in the current version of mutter as well so it isn't a regression.

The client needs to revert back to the non fractionally scaled interface during the resizing process to trigger the event. It also seems to affect GTK applications more dramatically than others.

**Review by jacobgkau — APPROVED** [review]
Tested together with https://github.com/pop-os/gnome-shell/pull/56.

**Pull request closed without merging**
