### PR TITLE
Mutter 42.5 Jammy Rebase

### PR DESCRIPTION
**Pull request by mmstick**
There's a lot of fixes in here. Testing should include the pop-shell checklist, too.

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Review by n3m0-22 — DISMISSED** [review]
Tested on `lemp11`, `gaze15`, and `Dev One`

All testing has passed. Looks good to me.

[gnome-shell-testing-mutter-42.5.txt](https://github.com/pop-os/mutter/files/10559967/gnome-shell-testing-mutter-42.5.txt)
[pop-shell-testing-mutter-42.5.txt](https://github.com/pop-os/mutter/files/10559968/pop-shell-testing-mutter-42.5.txt)

**Comment by n3m0-22** [comment]
There may be an issue with tiling. When I updated this morning Firefox needed to be restarted. After that tiling was all over the place. Resetting tiling did not fix it. I had to restart gnome. I'm looking into this further to see if I can recreate the issue, as well as specifically going over the tiling tests again.

**Comment by n3m0-22** [comment]
I have not been able to reproduce the issue. I've also checked the logs at the time it happened, but I am not seeing anything that stands out. Going over the tiling testing again has still passed.

As for the issue I saw earlier I will document it here as best I can in case it comes up again.

Steps to recreate:

Start with tiling enabled and two Firefox windows tiled side by side on the primary display and one Firefox window taking up the second display (in this case the built in display on the `lemp11`).

- `sudo apt-manage add popdev:rebase`
- `sudo apt update && sudo apt upgrade`
- `sudo reboot`
- `sudo apt-manage add popdev:master`
- `sudo apt update`
- `sudo apt-mark hold firefox`
- `sudo apt upgrade`
- `sudo reboot`
- `sudo apt-mark unhold firefox`
- `sudo apt install firefox`

Note: This never worked for me but it is as close as I can come to trying to recreate what happened.

At this point I was prompted to restart Firefox. This is what I saw. Tiling was enabled and `Multi-monitor Behavior` was set to `Workspaces on Primary Display Only`. The external display was set to Primary. Both were set to 100% scaling. The external display is connected over USB-C with PD.

Before restarting Firefox:
before_ff_restart

After restarting Firefox:
after_ff_restart

Toggling tiling on and off both through the menu and `Super` + `Y` did not change anything. Restarting gnome fixed it, and I never saw it happen again.

**Review by n3m0-22 — APPROVED** [review]
I'm approving this as neither I or @leviport could reproduce the issue, and all other testing has passed twice on multiple machines.

**Pull request merged**
