### PR TITLE
GNOME 3.38.2

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by ids1024** [comment]
Hopefully this fixes https://github.com/pop-os/gnome-control-center/issues/120.

**Comment by ids1024** [comment]
CI source build still seems to be failing for some reason.

**Comment by mmstick** [comment]
Patch debian/patches/x11-Add-support-for-fractional-scaling-using-Randr.patch does not exist

**Review by jacobgkau — APPROVED** [review]
Tested with https://github.com/pop-os/gnome-shell/pull/51.

**Pull request merged**
