### PR TITLE
fix: Revert changes that broke OSK

### PR DESCRIPTION
**Pull request by mmstick**
Debian patch version of #28 

Needs regression testing to see if this breaks anything.

Closes #28

### CODE REVIEW

**Comment by ruineka** [comment]
I applied this patch to mutter-master_jammy git on a fresh install of Pop OS 22.04 where the OSK could not be opened using the swipe gesture and it is now working as expected.

Tested on two devices: HP Envy x360 and OneXPlayer.

**Review by jackpot51 — DISMISSED** [review]

**Comment by mmstick** [comment]
One of the ARM64 tests is failing with this change. It passed on x86_64.

**Comment by mmstick** [comment]
Will retry the build just in case.

**Comment by mmstick** [comment]
It built that time.

**Review by n3m0-22 — APPROVED** [review]
22.04 tested on a Sony Vaio with touchscreen. The swipe up gesture is now working correctly to bring up the OSK.

**Comment by mmstick** [comment]
That's good news. Thanks @ruineka for the fix!

**Review by jackpot51 — APPROVED** [review]

**Comment by ruineka** [comment]
> That's good news. Thanks @ruineka for the fix!

No problem, thanks for the assistance with the quick merge. :)

**Comment by ruineka** [comment]
I updated my Aya Neo to see if the fixes made way to the 22.04 pipeline and it appears as though it is not. Will these changes make way to the LTS release or will I need to manually install the patched files?

**Comment by mmstick** [comment]
Packages are only released when the repo-release repository is updated. It's currently Saturday so any updates will have to wait for Monday.

**Comment by ruineka** [comment]
> Packages are only released when the repo-release repository is updated. It's currently Saturday so any updates will have to wait for Monday.

Fair enough. Thanks for the information.

**Pull request merged**
