### PR TITLE
Rebase to 42.1

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by n3m0-22** [comment]
Most testing passed, but I found a regression.

Steps to recreate:

1. Primary display is 4k set to 200% scaling
2. Have windows open on a few workspaces with tiling on
3. Plug in 1080 secondary display
4. Open a couple windows on the secondary display
5. Unplug the secondary display

The windows move back to the primary display to a new workspace. Then several things can happen to the windows on other workspaces, and not all of them happen each time. I have seen them no longer tiled, and toggling tiling on and off does not always fix it. Neither does restarting GNOME. Windows will be resized, or minimized. On occasion they stay tiled but the active hint is now on all windows in the workspace. The primary display will change scaling and or resolution. This only happens for me with the rebase installed.

Example of the primary display as the secondary is unplugged

https://user-images.githubusercontent.com/11048214/168374789-8cbde23a-83e1-4082-8ba5-5e7caaf66527.mp4

**Comment by n3m0-22** [comment]
On further testing under the same conditions all open windows have moved to the secondary display and all to the same workspace, but the secondary display is not being switched to primary. This has only happened a coupled time. Most of these issues seem to reproduce at random.

**Comment by mmstick** [comment]
Sounds very concerning. Is this without the pop-shell update from the staging branch? Does the pop-shell update in staging improve it?

**Comment by n3m0-22** [comment]
I haven't test that yet. I've been trying find other issues and double checking things, since these have been so inconsistent. I was worried other tests that passed might have just been luck. I'll give that a try now.

**Comment by n3m0-22** [comment]
With the new pop-shell most of what I was seeing is gone. I still see want can best be described as remnants of the issues, but they happen in a flash and correct themselves. I'll do more testing, but so far it seems this rebase is dependent on that update.

**Comment by n3m0-22** [comment]
The only issues I have seen and it has only happened twice so far. Is if I have windows open on the first two workspaces on the primary and windows open on the secondary monitor when unplugging the windows from the secondary get inserted into the second workspace on the primary monitor moving the windows that were there down a workspace.

**Comment by mmstick** [comment]
Is that happening without this change, too? May be an issue in pop-shell rather than mutter.

**Comment by n3m0-22** [comment]
I've tried it with and without and haven't been able to reproduce it.

**Comment by n3m0-22** [comment]
These packages are being held back.
`gir1.2-mutter-10` `libmutter-10-0`
Should that be happening?

**Comment by n3m0-22** [comment]
All but one of the issues I was seeing the other day have been fixed. This issue was hard to reproduce before, it happens every time now. I have been able to reproduce it on multiple machines with both switchable and non-switchable graphics, and in different graphics modes.

Steps to reproduce:

1. Enable tiling
2. Open a window on an empty workspace so it takes up with whole workspace
3. Try to minimize the window

The window will not minimize. This happens for every app I have tried. If you disable tiling the window will minimize. Opening another window while still in tiling mode so they each have half the workspace will allow the original window to minimize. Now the new window that is taking up the whole workspace will not minimize. 

Related issue steps to reproduce:

1. With tiling on and a window open using the whole workspace turn off tiling
2. Minimize the window
3. Turn tiling back on

The window does not stay minimized.

https://user-images.githubusercontent.com/11048214/168857517-016a0698-08d0-4dc8-bc4d-057e259eba61.mp4

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
All but one of the issues I was seeing the other day have been fixed. This issue was hard to reproduce before, it happens every time now. I have been able to reproduce it on multiple machines with both switchable and non-switchable graphics, and in different graphics modes.

Steps to reproduce:

1. Enable tiling
2. Open a window on an empty workspace so it takes up with whole workspace
3. Try to minimize the window

The window will not minimize. This happens for every app I have tried. If you disable tiling the window will minimize. Opening another window while still in tiling mode so they each have half the workspace will allow the original window to minimize. Now the new window that is taking up the whole workspace will not minimize. 

Related issue steps to reproduce:

1. With tiling on and a window open using the whole workspace turn off tiling
2. Minimize the window
3. Turn tiling back on

The window does not stay minimized.

https://user-images.githubusercontent.com/11048214/168858259-fbd7c197-96ef-492e-aafe-8422e01d079e.mp4

Log as it happens:

```
journalctl -o cat -n 0 -f "$(which gnome-shell)" | grep -v warning
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5628cb4c6350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5628ce1e12f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5628cdb46dc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5628cb4c6350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5628ce1e12f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5628cdb46dc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5628cb4c6350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5628ce1e12f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5628cdb46dc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5628cb4c6350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5628ce1e12f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5628cdb46dc0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5628cb4c6350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5628ce1e12f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5628cdb46dc0] is on because it needs an allocation.

```

**Comment by n3m0-22** [comment]
This issue may be related. I'm seeing this happen as well.
https://github.com/pop-os/shell/issues/1436

**Comment by mmstick** [comment]
Yeah, not a regression with current desktop

**Comment by n3m0-22** [comment]
It's odd because I tested it earlier with and without this PR and minimize worked on a single window in tilting mode, but now that I try it again without this PR I do have the problem. I'm not sure why, but yeah I guess it's not a regression. Thanks for pointing that out.

**Review by n3m0-22 — APPROVED** [review]

**Comment by mmstick** [comment]
I'll have a PR soon for pop-shell that fixes this and another issue.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
